name: Deploy Next.js app to different URLs

on:
  push:
    branches: [ dev, main ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/dev' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to test.midominio.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          destination: test.rodrigocsolari.com.ar
          method: "ms"
          commit_files: true

  deploy-main:
    runs-on: ubuntu-latest
    if: ${{ github.event.ref == 'refs/heads/main' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to midominio.com
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
          destination: rodrigocsolari.com.ar
          method: "ms"
          commit_files: true